gc:
  name: Gestão Carteiras - Módulo Commons

  queue-log: gc-logs
  queue:
    habilitado: false
    
security:
  jwt:
    secret: ${JWT_SECRET}
    
  
server:
  servlet:
    context-path: /commons
  port: 9090

spring:
  profiles:
#    active: ${ENV_PROFILE}
    active: PRD

  rabbitmq:
    host: ${AMQ_HOST}
    port: ${AMQ_PORT}
    username: ${AMQ_USER}
    password: ${AMQ_PASS}

